### ISSUE TITLE
Not taking custom known sections

### ISSUE THREAD

**Issue by SebCorbin** [pre-commit/mirrors-isort#5]
I struggle understanding how this hook works. It contains almost no code at all and I get different results running it whereas running isort standalone works OK.

Can I get any insight on how to get the same results?

For example my `[isort]` section does not seem to be taken into account...

**Comment by asottile** [comment]
This repository is a simple "mirror" repository, it is used for the installation side-effect of pulling in `isort`.  Here's where that gets set up: https://github.com/pre-commit/mirrors-isort/blob/f35773e46d096de5c45365f1a47eeeef36fc83ed/setup.py#L7

Note that `isort` itself is very bad at identifying imports and so you might be confusing that with not reading your configuration (?).  The suggested setup is to use this repository in conjunction with [`seed-isort-config`](https://github.com/pre-commit/mirrors-isort#classification-of-imports)

Let me know if there's more I can clarify here!

**Comment by asottile** [comment]
Here's an example configuration using this repository: https://github.com/tox-dev/tox/blob/1e8fa7ba9d88aefb1888cc0a951a252f7098f311/.pre-commit-config.yaml#L14-L22

**Comment by SebCorbin** [comment]
Thanks for your quick response. I understand now why it is so small... And thus I added your repo as a hook, which works great, but :

Here's my tox.ini section :

```
[isort]
combine_as_imports = true
multi_line_output = 5
include_trailing_comma = true
skip = migrations,.tox,.git,static,media
not_skip = __init__.py
known_first_party = accounts, common, document, gpa, messaging, planexo, worksite
known_django = django
known_third_party = braces,celery,compat,constance,crispy_forms,dal,dal_select2,dateutil,debug_toolbar,django_addanother,django_extensions,django_filters,django_slowtests,djcelery,el_pagination,envelope,extra_views,factory,faker,hijack_admin,ipdb,libarchive,line_profiler,localflavor,lxml,nested_formset,phonenumber_field,rainbowtests,selenium,versatileimagefield,weasyprint
sections = FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
```

`seed-isort-config` is not reading `known_django` and keeps adding it to `known_third_party`, is this normal?

For now I commented the `seed-isort-config` in my pre-commit config, and it works nicely

**Comment by asottile** [comment]
ah ok, let me move this to the appropriate project :)

**Comment by asottile** [comment]
actually I can't transfer across organizations.

Here's the duplicate issue though: https://github.com/asottile/seed-isort-config/issues/10
